// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Persistence;

#nullable disable

namespace ProductManagement.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Domain.Entities.InventoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Record", "Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d848715a-ca18-47b2-be95-a3ca5325848c"),
                            ProductId = new Guid("db976302-1ffe-4993-85f7-3ac1397cc5be"),
                            Quantity = 3m,
                            UnitPrice = 80.70m
                        },
                        new
                        {
                            Id = new Guid("9fa64946-0b65-44f8-959c-d58360918180"),
                            ProductId = new Guid("db976302-1ffe-4993-85f7-3ac1397cc5be"),
                            Quantity = 20m,
                            UnitPrice = 93.99m
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MeasurementUnit", "MeasurementUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "шт."
                        },
                        new
                        {
                            Id = 2,
                            Name = "м"
                        },
                        new
                        {
                            Id = 3,
                            Name = "кг"
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Product", "Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db976302-1ffe-4993-85f7-3ac1397cc5be"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Пара кожанных перчаток с заячьим мехом",
                            LastModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementUnitId = 1,
                            Name = "Перчатки",
                            OwnerId = new Guid("160be924-907f-4d70-d15c-08de2383d454")
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.ProductOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeactivated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("ProductOwner", "Inventory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("160be924-907f-4d70-d15c-08de2383d454"),
                            IsDeactivated = false,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.InventoryRecord", b =>
                {
                    b.HasOne("ProductManagement.Domain.Entities.Product", "Product")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductManagement.Domain.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProductManagement.Domain.Entities.ProductOwner", "Owner")
                        .WithMany("Products")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.Product", b =>
                {
                    b.Navigation("InventoryRecords");
                });

            modelBuilder.Entity("ProductManagement.Domain.Entities.ProductOwner", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
